output "application_id" {
  description = "The application ID (client ID) of the application for which to create a service principal."
  value       = azuread_service_principal.this.application_id
}

output "azuread_application_password" {
  description = "The password for this application, which is generated by Azure Active Directory."
  sensitive   = true
  value       = azuread_application_password.this.value
}

output "resource_group_name" {
  description = "The resource group name where resources are created"
  value       = data.azurerm_resource_group.this.name
}

output "tenant_id" {
  description = "The tenant ID of the authenticated principal."
  value       = data.azuread_client_config.current.tenant_id
}


output "data_collection_endpoint_id" {
  description = "The ID of the Data Collection Endpoint"
  value       = azurerm_monitor_data_collection_endpoint.this.id
}

output "data_collection_rule_id" {
  description = "The ID of the data collection rule"
  value       = azurerm_monitor_data_collection_rule.this.id
}

output "immutable_id" {
  description = "The immutable ID of the Data Collection Rule."
  value       = azurerm_monitor_data_collection_rule.this.immutable_id
}

output "logs_ingestion_endpoint" {
  description = "The endpoint used for ingesting logs, e.g., https://mydce-abcd.eastus-1.ingest.monitor.azure.com"
  value       = azurerm_monitor_data_collection_endpoint.this.logs_ingestion_endpoint
}

output "workspace_id" {
  description = "The workspace id"
  value       = azurerm_log_analytics_workspace.this.id
}

output "created_tables" {
  description = "The tables that were created in the azure log analytics workspace"
  value = [
    for t in local.custom_tables :
    t.table_name
    if t.enabled
  ]
}

output "data_collection_endpoints" {
  description = "API documentation can be found here: https://learn.microsoft.com/en-us/rest/api/monitor/data-collection-rules"
  value = {
    for t in local.custom_tables :
    t.table_name => {
      table_name   = t.table_name
      endpoint_url = "${azurerm_monitor_data_collection_endpoint.this.logs_ingestion_endpoint}/dataCollectionRules/${azurerm_monitor_data_collection_rule.this.immutable_id}/streams/Custom-${t.table_name}?api-version=${var.api_version}"
    }
    if t.enabled
  }
}
